// -----------------------------------------------------------------------------
// @file: app/api/profile/two-factor/qr/route.ts
// @purpose: Render a QR code for a TOTP `otpauth://` URI as a PNG image. Used
//           by the /profile two-factor section so the TOTP secret never
//           leaves our infrastructure (third-party QR APIs would log every
//           secret a user enrolls).
//
//           Expects: ?uri=<urlencoded otpauth://...>
//           Auth:    any signed-in user — there's no per-user data in the
//                    response, just QR pixels generated from the URI you
//                    submit. The auth gate exists so unauthenticated traffic
//                    can't burn server CPU on QR rendering.
// -----------------------------------------------------------------------------

import { NextRequest, NextResponse } from "next/server";
import QRCode from "qrcode";

import { getCurrentUserOrThrow } from "@/lib/auth";

export async function GET(req: NextRequest) {
  try {
    // Require auth. The URI itself was generated by BetterAuth for THIS
    // user when they hit /two-factor/enable, so a signed-in user requesting
    // a QR for that URI is the expected case. Unauthenticated callers
    // get nothing — defends the route from CPU-burn attacks.
    await getCurrentUserOrThrow();

    const { searchParams } = new URL(req.url);
    const uri = searchParams.get("uri");

    if (!uri) {
      return NextResponse.json({ error: "uri is required" }, { status: 400 });
    }
    // Refuse anything that isn't a TOTP otpauth URI. Stops the endpoint
    // from being abused as a generic QR generator (which would fan out
    // arbitrary content via our origin).
    if (!uri.startsWith("otpauth://")) {
      return NextResponse.json({ error: "uri must be an otpauth:// URI" }, { status: 400 });
    }
    if (uri.length > 2000) {
      return NextResponse.json({ error: "uri too long" }, { status: 400 });
    }

    const png = await QRCode.toBuffer(uri, {
      errorCorrectionLevel: "M",
      margin: 1,
      scale: 6,
      type: "png",
    });

    return new NextResponse(png as unknown as BodyInit, {
      status: 200,
      headers: {
        "Content-Type": "image/png",
        // Cache aggressively per-URI: the QR for a given otpauth URI never
        // changes. The URI is itself short-lived (BetterAuth invalidates
        // it on enable + verify), so this caches at most for the duration
        // of one enrollment attempt.
        "Cache-Control": "private, max-age=300, must-revalidate",
      },
    });
  } catch (err: unknown) {
    if ((err as { code?: string })?.code === "UNAUTHENTICATED") {
      return NextResponse.json({ error: "Unauthenticated" }, { status: 401 });
    }
    console.error("[GET /api/profile/two-factor/qr] error", err);
    return NextResponse.json({ error: "Failed to render QR" }, { status: 500 });
  }
}
