// -----------------------------------------------------------------------------
// @file: lib/countries.ts
// @purpose: Static reference data for the talent application form's country,
//           WhatsApp dial-code, and timezone selectors. One source of truth so
//           the dropdowns can't drift out of sync (e.g. country = "Türkiye"
//           but timezone offered = "America/New_York").
//
//           Coverage: 250 entries from ISO 3166-1 alpha-2. Each row carries:
//             - iso2:     stable lookup key for the form
//             - name:     display string (English; localized labels are a
//                         future Intl.DisplayNames concern)
//             - dialCode: E.164 country code with a leading "+"
//             - timezones: IANA names from zone1970.tab. Single-zone
//                         countries get one entry; multi-zone (US, RU, AU,
//                         etc.) carry the full set so the form can
//                         constrain the timezone <select> after country
//                         selection.
//
//           This file is hand-curated, not generated. The IANA tzdb does
//           shift occasionally (a country gets a new zone, splits, or
//           renames) but at the rate of single-digit changes per year. A
//           lockfile-style data file is more transparent than a runtime
//           dependency for ~5 KB of data we only ever read.
// -----------------------------------------------------------------------------

export type CountryRow = {
  /** ISO 3166-1 alpha-2 code. Stable across renames (e.g. "TR" stays "TR"
   *  even though "Turkey" → "Türkiye" in display). Use this as the form
   *  state's source of truth and as the lookup key into other maps. */
  iso2: string;
  /** Display name. English-only for now. */
  name: string;
  /** E.164 country calling code with a leading "+". Multi-code rows
   *  (countries that share a code like the NANP) each carry the same
   *  string — that's fine, the user picks by country, not by raw code. */
  dialCode: string;
  /** IANA timezone identifiers used in this country. Single-zone
   *  countries get one entry; the form auto-selects when length === 1. */
  timezones: string[];
};

export const COUNTRIES: CountryRow[] = [
  { iso2: "AD", name: "Andorra", dialCode: "+376", timezones: ["Europe/Andorra"] },
  { iso2: "AE", name: "United Arab Emirates", dialCode: "+971", timezones: ["Asia/Dubai"] },
  { iso2: "AF", name: "Afghanistan", dialCode: "+93", timezones: ["Asia/Kabul"] },
  { iso2: "AG", name: "Antigua and Barbuda", dialCode: "+1", timezones: ["America/Antigua"] },
  { iso2: "AI", name: "Anguilla", dialCode: "+1", timezones: ["America/Anguilla"] },
  { iso2: "AL", name: "Albania", dialCode: "+355", timezones: ["Europe/Tirane"] },
  { iso2: "AM", name: "Armenia", dialCode: "+374", timezones: ["Asia/Yerevan"] },
  { iso2: "AO", name: "Angola", dialCode: "+244", timezones: ["Africa/Luanda"] },
  {
    iso2: "AQ",
    name: "Antarctica",
    dialCode: "+672",
    timezones: [
      "Antarctica/McMurdo",
      "Antarctica/Casey",
      "Antarctica/Davis",
      "Antarctica/Mawson",
      "Antarctica/Palmer",
      "Antarctica/Rothera",
      "Antarctica/Syowa",
      "Antarctica/Troll",
      "Antarctica/Vostok",
    ],
  },
  {
    iso2: "AR",
    name: "Argentina",
    dialCode: "+54",
    timezones: [
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Cordoba",
      "America/Argentina/Salta",
      "America/Argentina/Jujuy",
      "America/Argentina/Tucuman",
      "America/Argentina/Catamarca",
      "America/Argentina/La_Rioja",
      "America/Argentina/San_Juan",
      "America/Argentina/Mendoza",
      "America/Argentina/San_Luis",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Ushuaia",
    ],
  },
  { iso2: "AS", name: "American Samoa", dialCode: "+1", timezones: ["Pacific/Pago_Pago"] },
  { iso2: "AT", name: "Austria", dialCode: "+43", timezones: ["Europe/Vienna"] },
  {
    iso2: "AU",
    name: "Australia",
    dialCode: "+61",
    timezones: [
      "Australia/Sydney",
      "Australia/Melbourne",
      "Australia/Brisbane",
      "Australia/Perth",
      "Australia/Adelaide",
      "Australia/Hobart",
      "Australia/Darwin",
      "Australia/Lord_Howe",
      "Australia/Eucla",
      "Australia/Lindeman",
      "Antarctica/Macquarie",
    ],
  },
  { iso2: "AW", name: "Aruba", dialCode: "+297", timezones: ["America/Aruba"] },
  { iso2: "AX", name: "Åland Islands", dialCode: "+358", timezones: ["Europe/Mariehamn"] },
  { iso2: "AZ", name: "Azerbaijan", dialCode: "+994", timezones: ["Asia/Baku"] },
  { iso2: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", timezones: ["Europe/Sarajevo"] },
  { iso2: "BB", name: "Barbados", dialCode: "+1", timezones: ["America/Barbados"] },
  { iso2: "BD", name: "Bangladesh", dialCode: "+880", timezones: ["Asia/Dhaka"] },
  { iso2: "BE", name: "Belgium", dialCode: "+32", timezones: ["Europe/Brussels"] },
  { iso2: "BF", name: "Burkina Faso", dialCode: "+226", timezones: ["Africa/Ouagadougou"] },
  { iso2: "BG", name: "Bulgaria", dialCode: "+359", timezones: ["Europe/Sofia"] },
  { iso2: "BH", name: "Bahrain", dialCode: "+973", timezones: ["Asia/Bahrain"] },
  { iso2: "BI", name: "Burundi", dialCode: "+257", timezones: ["Africa/Bujumbura"] },
  { iso2: "BJ", name: "Benin", dialCode: "+229", timezones: ["Africa/Porto-Novo"] },
  { iso2: "BL", name: "Saint Barthélemy", dialCode: "+590", timezones: ["America/St_Barthelemy"] },
  { iso2: "BM", name: "Bermuda", dialCode: "+1", timezones: ["Atlantic/Bermuda"] },
  { iso2: "BN", name: "Brunei", dialCode: "+673", timezones: ["Asia/Brunei"] },
  { iso2: "BO", name: "Bolivia", dialCode: "+591", timezones: ["America/La_Paz"] },
  {
    iso2: "BQ",
    name: "Caribbean Netherlands",
    dialCode: "+599",
    timezones: ["America/Kralendijk"],
  },
  {
    iso2: "BR",
    name: "Brazil",
    dialCode: "+55",
    timezones: [
      "America/Sao_Paulo",
      "America/Bahia",
      "America/Fortaleza",
      "America/Recife",
      "America/Belem",
      "America/Maceio",
      "America/Araguaina",
      "America/Manaus",
      "America/Campo_Grande",
      "America/Cuiaba",
      "America/Boa_Vista",
      "America/Porto_Velho",
      "America/Rio_Branco",
      "America/Eirunepe",
      "America/Noronha",
      "America/Santarem",
    ],
  },
  { iso2: "BS", name: "Bahamas", dialCode: "+1", timezones: ["America/Nassau"] },
  { iso2: "BT", name: "Bhutan", dialCode: "+975", timezones: ["Asia/Thimphu"] },
  { iso2: "BW", name: "Botswana", dialCode: "+267", timezones: ["Africa/Gaborone"] },
  { iso2: "BY", name: "Belarus", dialCode: "+375", timezones: ["Europe/Minsk"] },
  { iso2: "BZ", name: "Belize", dialCode: "+501", timezones: ["America/Belize"] },
  {
    iso2: "CA",
    name: "Canada",
    dialCode: "+1",
    timezones: [
      "America/Toronto",
      "America/Vancouver",
      "America/Edmonton",
      "America/Winnipeg",
      "America/Halifax",
      "America/St_Johns",
      "America/Regina",
      "America/Whitehorse",
      "America/Yellowknife",
      "America/Iqaluit",
      "America/Glace_Bay",
      "America/Goose_Bay",
      "America/Moncton",
      "America/Blanc-Sablon",
      "America/Atikokan",
      "America/Rainy_River",
      "America/Resolute",
      "America/Rankin_Inlet",
      "America/Cambridge_Bay",
      "America/Inuvik",
      "America/Dawson",
      "America/Dawson_Creek",
      "America/Fort_Nelson",
      "America/Creston",
      "America/Swift_Current",
      "America/Nipigon",
      "America/Thunder_Bay",
      "America/Pangnirtung",
    ],
  },
  { iso2: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61", timezones: ["Indian/Cocos"] },
  {
    iso2: "CD",
    name: "DR Congo",
    dialCode: "+243",
    timezones: ["Africa/Kinshasa", "Africa/Lubumbashi"],
  },
  { iso2: "CF", name: "Central African Republic", dialCode: "+236", timezones: ["Africa/Bangui"] },
  {
    iso2: "CG",
    name: "Republic of the Congo",
    dialCode: "+242",
    timezones: ["Africa/Brazzaville"],
  },
  { iso2: "CH", name: "Switzerland", dialCode: "+41", timezones: ["Europe/Zurich"] },
  { iso2: "CI", name: "Côte d'Ivoire", dialCode: "+225", timezones: ["Africa/Abidjan"] },
  { iso2: "CK", name: "Cook Islands", dialCode: "+682", timezones: ["Pacific/Rarotonga"] },
  {
    iso2: "CL",
    name: "Chile",
    dialCode: "+56",
    timezones: ["America/Santiago", "America/Punta_Arenas", "Pacific/Easter"],
  },
  { iso2: "CM", name: "Cameroon", dialCode: "+237", timezones: ["Africa/Douala"] },
  { iso2: "CN", name: "China", dialCode: "+86", timezones: ["Asia/Shanghai", "Asia/Urumqi"] },
  { iso2: "CO", name: "Colombia", dialCode: "+57", timezones: ["America/Bogota"] },
  { iso2: "CR", name: "Costa Rica", dialCode: "+506", timezones: ["America/Costa_Rica"] },
  { iso2: "CU", name: "Cuba", dialCode: "+53", timezones: ["America/Havana"] },
  { iso2: "CV", name: "Cape Verde", dialCode: "+238", timezones: ["Atlantic/Cape_Verde"] },
  { iso2: "CW", name: "Curaçao", dialCode: "+599", timezones: ["America/Curacao"] },
  { iso2: "CX", name: "Christmas Island", dialCode: "+61", timezones: ["Indian/Christmas"] },
  { iso2: "CY", name: "Cyprus", dialCode: "+357", timezones: ["Asia/Nicosia", "Asia/Famagusta"] },
  { iso2: "CZ", name: "Czechia", dialCode: "+420", timezones: ["Europe/Prague"] },
  { iso2: "DE", name: "Germany", dialCode: "+49", timezones: ["Europe/Berlin", "Europe/Busingen"] },
  { iso2: "DJ", name: "Djibouti", dialCode: "+253", timezones: ["Africa/Djibouti"] },
  { iso2: "DK", name: "Denmark", dialCode: "+45", timezones: ["Europe/Copenhagen"] },
  { iso2: "DM", name: "Dominica", dialCode: "+1", timezones: ["America/Dominica"] },
  { iso2: "DO", name: "Dominican Republic", dialCode: "+1", timezones: ["America/Santo_Domingo"] },
  { iso2: "DZ", name: "Algeria", dialCode: "+213", timezones: ["Africa/Algiers"] },
  {
    iso2: "EC",
    name: "Ecuador",
    dialCode: "+593",
    timezones: ["America/Guayaquil", "Pacific/Galapagos"],
  },
  { iso2: "EE", name: "Estonia", dialCode: "+372", timezones: ["Europe/Tallinn"] },
  { iso2: "EG", name: "Egypt", dialCode: "+20", timezones: ["Africa/Cairo"] },
  { iso2: "EH", name: "Western Sahara", dialCode: "+212", timezones: ["Africa/El_Aaiun"] },
  { iso2: "ER", name: "Eritrea", dialCode: "+291", timezones: ["Africa/Asmara"] },
  {
    iso2: "ES",
    name: "Spain",
    dialCode: "+34",
    timezones: ["Europe/Madrid", "Africa/Ceuta", "Atlantic/Canary"],
  },
  { iso2: "ET", name: "Ethiopia", dialCode: "+251", timezones: ["Africa/Addis_Ababa"] },
  { iso2: "FI", name: "Finland", dialCode: "+358", timezones: ["Europe/Helsinki"] },
  { iso2: "FJ", name: "Fiji", dialCode: "+679", timezones: ["Pacific/Fiji"] },
  { iso2: "FK", name: "Falkland Islands", dialCode: "+500", timezones: ["Atlantic/Stanley"] },
  {
    iso2: "FM",
    name: "Micronesia",
    dialCode: "+691",
    timezones: ["Pacific/Pohnpei", "Pacific/Kosrae", "Pacific/Chuuk"],
  },
  { iso2: "FO", name: "Faroe Islands", dialCode: "+298", timezones: ["Atlantic/Faroe"] },
  { iso2: "FR", name: "France", dialCode: "+33", timezones: ["Europe/Paris"] },
  { iso2: "GA", name: "Gabon", dialCode: "+241", timezones: ["Africa/Libreville"] },
  { iso2: "GB", name: "United Kingdom", dialCode: "+44", timezones: ["Europe/London"] },
  { iso2: "GD", name: "Grenada", dialCode: "+1", timezones: ["America/Grenada"] },
  { iso2: "GE", name: "Georgia", dialCode: "+995", timezones: ["Asia/Tbilisi"] },
  { iso2: "GF", name: "French Guiana", dialCode: "+594", timezones: ["America/Cayenne"] },
  { iso2: "GG", name: "Guernsey", dialCode: "+44", timezones: ["Europe/Guernsey"] },
  { iso2: "GH", name: "Ghana", dialCode: "+233", timezones: ["Africa/Accra"] },
  { iso2: "GI", name: "Gibraltar", dialCode: "+350", timezones: ["Europe/Gibraltar"] },
  {
    iso2: "GL",
    name: "Greenland",
    dialCode: "+299",
    timezones: ["America/Nuuk", "America/Danmarkshavn", "America/Scoresbysund", "America/Thule"],
  },
  { iso2: "GM", name: "Gambia", dialCode: "+220", timezones: ["Africa/Banjul"] },
  { iso2: "GN", name: "Guinea", dialCode: "+224", timezones: ["Africa/Conakry"] },
  { iso2: "GP", name: "Guadeloupe", dialCode: "+590", timezones: ["America/Guadeloupe"] },
  { iso2: "GQ", name: "Equatorial Guinea", dialCode: "+240", timezones: ["Africa/Malabo"] },
  { iso2: "GR", name: "Greece", dialCode: "+30", timezones: ["Europe/Athens"] },
  { iso2: "GS", name: "South Georgia", dialCode: "+500", timezones: ["Atlantic/South_Georgia"] },
  { iso2: "GT", name: "Guatemala", dialCode: "+502", timezones: ["America/Guatemala"] },
  { iso2: "GU", name: "Guam", dialCode: "+1", timezones: ["Pacific/Guam"] },
  { iso2: "GW", name: "Guinea-Bissau", dialCode: "+245", timezones: ["Africa/Bissau"] },
  { iso2: "GY", name: "Guyana", dialCode: "+592", timezones: ["America/Guyana"] },
  { iso2: "HK", name: "Hong Kong", dialCode: "+852", timezones: ["Asia/Hong_Kong"] },
  { iso2: "HN", name: "Honduras", dialCode: "+504", timezones: ["America/Tegucigalpa"] },
  { iso2: "HR", name: "Croatia", dialCode: "+385", timezones: ["Europe/Zagreb"] },
  { iso2: "HT", name: "Haiti", dialCode: "+509", timezones: ["America/Port-au-Prince"] },
  { iso2: "HU", name: "Hungary", dialCode: "+36", timezones: ["Europe/Budapest"] },
  {
    iso2: "ID",
    name: "Indonesia",
    dialCode: "+62",
    timezones: ["Asia/Jakarta", "Asia/Pontianak", "Asia/Makassar", "Asia/Jayapura"],
  },
  { iso2: "IE", name: "Ireland", dialCode: "+353", timezones: ["Europe/Dublin"] },
  { iso2: "IL", name: "Israel", dialCode: "+972", timezones: ["Asia/Jerusalem"] },
  { iso2: "IM", name: "Isle of Man", dialCode: "+44", timezones: ["Europe/Isle_of_Man"] },
  { iso2: "IN", name: "India", dialCode: "+91", timezones: ["Asia/Kolkata"] },
  {
    iso2: "IO",
    name: "British Indian Ocean Territory",
    dialCode: "+246",
    timezones: ["Indian/Chagos"],
  },
  { iso2: "IQ", name: "Iraq", dialCode: "+964", timezones: ["Asia/Baghdad"] },
  { iso2: "IR", name: "Iran", dialCode: "+98", timezones: ["Asia/Tehran"] },
  { iso2: "IS", name: "Iceland", dialCode: "+354", timezones: ["Atlantic/Reykjavik"] },
  { iso2: "IT", name: "Italy", dialCode: "+39", timezones: ["Europe/Rome"] },
  { iso2: "JE", name: "Jersey", dialCode: "+44", timezones: ["Europe/Jersey"] },
  { iso2: "JM", name: "Jamaica", dialCode: "+1", timezones: ["America/Jamaica"] },
  { iso2: "JO", name: "Jordan", dialCode: "+962", timezones: ["Asia/Amman"] },
  { iso2: "JP", name: "Japan", dialCode: "+81", timezones: ["Asia/Tokyo"] },
  { iso2: "KE", name: "Kenya", dialCode: "+254", timezones: ["Africa/Nairobi"] },
  { iso2: "KG", name: "Kyrgyzstan", dialCode: "+996", timezones: ["Asia/Bishkek"] },
  { iso2: "KH", name: "Cambodia", dialCode: "+855", timezones: ["Asia/Phnom_Penh"] },
  {
    iso2: "KI",
    name: "Kiribati",
    dialCode: "+686",
    timezones: ["Pacific/Tarawa", "Pacific/Kanton", "Pacific/Kiritimati"],
  },
  { iso2: "KM", name: "Comoros", dialCode: "+269", timezones: ["Indian/Comoro"] },
  { iso2: "KN", name: "Saint Kitts and Nevis", dialCode: "+1", timezones: ["America/St_Kitts"] },
  { iso2: "KP", name: "North Korea", dialCode: "+850", timezones: ["Asia/Pyongyang"] },
  { iso2: "KR", name: "South Korea", dialCode: "+82", timezones: ["Asia/Seoul"] },
  { iso2: "KW", name: "Kuwait", dialCode: "+965", timezones: ["Asia/Kuwait"] },
  { iso2: "KY", name: "Cayman Islands", dialCode: "+1", timezones: ["America/Cayman"] },
  {
    iso2: "KZ",
    name: "Kazakhstan",
    dialCode: "+7",
    timezones: [
      "Asia/Almaty",
      "Asia/Qyzylorda",
      "Asia/Aqtobe",
      "Asia/Aqtau",
      "Asia/Atyrau",
      "Asia/Oral",
    ],
  },
  { iso2: "LA", name: "Laos", dialCode: "+856", timezones: ["Asia/Vientiane"] },
  { iso2: "LB", name: "Lebanon", dialCode: "+961", timezones: ["Asia/Beirut"] },
  { iso2: "LC", name: "Saint Lucia", dialCode: "+1", timezones: ["America/St_Lucia"] },
  { iso2: "LI", name: "Liechtenstein", dialCode: "+423", timezones: ["Europe/Vaduz"] },
  { iso2: "LK", name: "Sri Lanka", dialCode: "+94", timezones: ["Asia/Colombo"] },
  { iso2: "LR", name: "Liberia", dialCode: "+231", timezones: ["Africa/Monrovia"] },
  { iso2: "LS", name: "Lesotho", dialCode: "+266", timezones: ["Africa/Maseru"] },
  { iso2: "LT", name: "Lithuania", dialCode: "+370", timezones: ["Europe/Vilnius"] },
  { iso2: "LU", name: "Luxembourg", dialCode: "+352", timezones: ["Europe/Luxembourg"] },
  { iso2: "LV", name: "Latvia", dialCode: "+371", timezones: ["Europe/Riga"] },
  { iso2: "LY", name: "Libya", dialCode: "+218", timezones: ["Africa/Tripoli"] },
  { iso2: "MA", name: "Morocco", dialCode: "+212", timezones: ["Africa/Casablanca"] },
  { iso2: "MC", name: "Monaco", dialCode: "+377", timezones: ["Europe/Monaco"] },
  { iso2: "MD", name: "Moldova", dialCode: "+373", timezones: ["Europe/Chisinau"] },
  { iso2: "ME", name: "Montenegro", dialCode: "+382", timezones: ["Europe/Podgorica"] },
  { iso2: "MF", name: "Saint Martin", dialCode: "+590", timezones: ["America/Marigot"] },
  { iso2: "MG", name: "Madagascar", dialCode: "+261", timezones: ["Indian/Antananarivo"] },
  {
    iso2: "MH",
    name: "Marshall Islands",
    dialCode: "+692",
    timezones: ["Pacific/Majuro", "Pacific/Kwajalein"],
  },
  { iso2: "MK", name: "North Macedonia", dialCode: "+389", timezones: ["Europe/Skopje"] },
  { iso2: "ML", name: "Mali", dialCode: "+223", timezones: ["Africa/Bamako"] },
  { iso2: "MM", name: "Myanmar", dialCode: "+95", timezones: ["Asia/Yangon"] },
  {
    iso2: "MN",
    name: "Mongolia",
    dialCode: "+976",
    timezones: ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"],
  },
  { iso2: "MO", name: "Macau", dialCode: "+853", timezones: ["Asia/Macau"] },
  { iso2: "MP", name: "Northern Mariana Islands", dialCode: "+1", timezones: ["Pacific/Saipan"] },
  { iso2: "MQ", name: "Martinique", dialCode: "+596", timezones: ["America/Martinique"] },
  { iso2: "MR", name: "Mauritania", dialCode: "+222", timezones: ["Africa/Nouakchott"] },
  { iso2: "MS", name: "Montserrat", dialCode: "+1", timezones: ["America/Montserrat"] },
  { iso2: "MT", name: "Malta", dialCode: "+356", timezones: ["Europe/Malta"] },
  { iso2: "MU", name: "Mauritius", dialCode: "+230", timezones: ["Indian/Mauritius"] },
  { iso2: "MV", name: "Maldives", dialCode: "+960", timezones: ["Indian/Maldives"] },
  { iso2: "MW", name: "Malawi", dialCode: "+265", timezones: ["Africa/Blantyre"] },
  {
    iso2: "MX",
    name: "Mexico",
    dialCode: "+52",
    timezones: [
      "America/Mexico_City",
      "America/Cancun",
      "America/Merida",
      "America/Monterrey",
      "America/Matamoros",
      "America/Mazatlan",
      "America/Chihuahua",
      "America/Ojinaga",
      "America/Hermosillo",
      "America/Tijuana",
      "America/Bahia_Banderas",
    ],
  },
  {
    iso2: "MY",
    name: "Malaysia",
    dialCode: "+60",
    timezones: ["Asia/Kuala_Lumpur", "Asia/Kuching"],
  },
  { iso2: "MZ", name: "Mozambique", dialCode: "+258", timezones: ["Africa/Maputo"] },
  { iso2: "NA", name: "Namibia", dialCode: "+264", timezones: ["Africa/Windhoek"] },
  { iso2: "NC", name: "New Caledonia", dialCode: "+687", timezones: ["Pacific/Noumea"] },
  { iso2: "NE", name: "Niger", dialCode: "+227", timezones: ["Africa/Niamey"] },
  { iso2: "NF", name: "Norfolk Island", dialCode: "+672", timezones: ["Pacific/Norfolk"] },
  { iso2: "NG", name: "Nigeria", dialCode: "+234", timezones: ["Africa/Lagos"] },
  { iso2: "NI", name: "Nicaragua", dialCode: "+505", timezones: ["America/Managua"] },
  { iso2: "NL", name: "Netherlands", dialCode: "+31", timezones: ["Europe/Amsterdam"] },
  { iso2: "NO", name: "Norway", dialCode: "+47", timezones: ["Europe/Oslo"] },
  { iso2: "NP", name: "Nepal", dialCode: "+977", timezones: ["Asia/Kathmandu"] },
  { iso2: "NR", name: "Nauru", dialCode: "+674", timezones: ["Pacific/Nauru"] },
  { iso2: "NU", name: "Niue", dialCode: "+683", timezones: ["Pacific/Niue"] },
  {
    iso2: "NZ",
    name: "New Zealand",
    dialCode: "+64",
    timezones: ["Pacific/Auckland", "Pacific/Chatham"],
  },
  { iso2: "OM", name: "Oman", dialCode: "+968", timezones: ["Asia/Muscat"] },
  { iso2: "PA", name: "Panama", dialCode: "+507", timezones: ["America/Panama"] },
  { iso2: "PE", name: "Peru", dialCode: "+51", timezones: ["America/Lima"] },
  {
    iso2: "PF",
    name: "French Polynesia",
    dialCode: "+689",
    timezones: ["Pacific/Tahiti", "Pacific/Marquesas", "Pacific/Gambier"],
  },
  {
    iso2: "PG",
    name: "Papua New Guinea",
    dialCode: "+675",
    timezones: ["Pacific/Port_Moresby", "Pacific/Bougainville"],
  },
  { iso2: "PH", name: "Philippines", dialCode: "+63", timezones: ["Asia/Manila"] },
  { iso2: "PK", name: "Pakistan", dialCode: "+92", timezones: ["Asia/Karachi"] },
  { iso2: "PL", name: "Poland", dialCode: "+48", timezones: ["Europe/Warsaw"] },
  {
    iso2: "PM",
    name: "Saint Pierre and Miquelon",
    dialCode: "+508",
    timezones: ["America/Miquelon"],
  },
  { iso2: "PN", name: "Pitcairn Islands", dialCode: "+64", timezones: ["Pacific/Pitcairn"] },
  { iso2: "PR", name: "Puerto Rico", dialCode: "+1", timezones: ["America/Puerto_Rico"] },
  { iso2: "PS", name: "Palestine", dialCode: "+970", timezones: ["Asia/Gaza", "Asia/Hebron"] },
  {
    iso2: "PT",
    name: "Portugal",
    dialCode: "+351",
    timezones: ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"],
  },
  { iso2: "PW", name: "Palau", dialCode: "+680", timezones: ["Pacific/Palau"] },
  { iso2: "PY", name: "Paraguay", dialCode: "+595", timezones: ["America/Asuncion"] },
  { iso2: "QA", name: "Qatar", dialCode: "+974", timezones: ["Asia/Qatar"] },
  { iso2: "RE", name: "Réunion", dialCode: "+262", timezones: ["Indian/Reunion"] },
  { iso2: "RO", name: "Romania", dialCode: "+40", timezones: ["Europe/Bucharest"] },
  { iso2: "RS", name: "Serbia", dialCode: "+381", timezones: ["Europe/Belgrade"] },
  {
    iso2: "RU",
    name: "Russia",
    dialCode: "+7",
    timezones: [
      "Europe/Moscow",
      "Europe/Kaliningrad",
      "Europe/Samara",
      "Europe/Volgograd",
      "Europe/Astrakhan",
      "Europe/Saratov",
      "Europe/Ulyanovsk",
      "Europe/Kirov",
      "Asia/Yekaterinburg",
      "Asia/Omsk",
      "Asia/Novosibirsk",
      "Asia/Barnaul",
      "Asia/Tomsk",
      "Asia/Novokuznetsk",
      "Asia/Krasnoyarsk",
      "Asia/Irkutsk",
      "Asia/Chita",
      "Asia/Yakutsk",
      "Asia/Khandyga",
      "Asia/Vladivostok",
      "Asia/Ust-Nera",
      "Asia/Magadan",
      "Asia/Sakhalin",
      "Asia/Srednekolymsk",
      "Asia/Kamchatka",
      "Asia/Anadyr",
    ],
  },
  { iso2: "RW", name: "Rwanda", dialCode: "+250", timezones: ["Africa/Kigali"] },
  { iso2: "SA", name: "Saudi Arabia", dialCode: "+966", timezones: ["Asia/Riyadh"] },
  { iso2: "SB", name: "Solomon Islands", dialCode: "+677", timezones: ["Pacific/Guadalcanal"] },
  { iso2: "SC", name: "Seychelles", dialCode: "+248", timezones: ["Indian/Mahe"] },
  { iso2: "SD", name: "Sudan", dialCode: "+249", timezones: ["Africa/Khartoum"] },
  { iso2: "SE", name: "Sweden", dialCode: "+46", timezones: ["Europe/Stockholm"] },
  { iso2: "SG", name: "Singapore", dialCode: "+65", timezones: ["Asia/Singapore"] },
  { iso2: "SH", name: "Saint Helena", dialCode: "+290", timezones: ["Atlantic/St_Helena"] },
  { iso2: "SI", name: "Slovenia", dialCode: "+386", timezones: ["Europe/Ljubljana"] },
  {
    iso2: "SJ",
    name: "Svalbard and Jan Mayen",
    dialCode: "+47",
    timezones: ["Arctic/Longyearbyen"],
  },
  { iso2: "SK", name: "Slovakia", dialCode: "+421", timezones: ["Europe/Bratislava"] },
  { iso2: "SL", name: "Sierra Leone", dialCode: "+232", timezones: ["Africa/Freetown"] },
  { iso2: "SM", name: "San Marino", dialCode: "+378", timezones: ["Europe/San_Marino"] },
  { iso2: "SN", name: "Senegal", dialCode: "+221", timezones: ["Africa/Dakar"] },
  { iso2: "SO", name: "Somalia", dialCode: "+252", timezones: ["Africa/Mogadishu"] },
  { iso2: "SR", name: "Suriname", dialCode: "+597", timezones: ["America/Paramaribo"] },
  { iso2: "SS", name: "South Sudan", dialCode: "+211", timezones: ["Africa/Juba"] },
  { iso2: "ST", name: "São Tomé and Príncipe", dialCode: "+239", timezones: ["Africa/Sao_Tome"] },
  { iso2: "SV", name: "El Salvador", dialCode: "+503", timezones: ["America/El_Salvador"] },
  { iso2: "SX", name: "Sint Maarten", dialCode: "+1", timezones: ["America/Lower_Princes"] },
  { iso2: "SY", name: "Syria", dialCode: "+963", timezones: ["Asia/Damascus"] },
  { iso2: "SZ", name: "Eswatini", dialCode: "+268", timezones: ["Africa/Mbabane"] },
  { iso2: "TC", name: "Turks and Caicos", dialCode: "+1", timezones: ["America/Grand_Turk"] },
  { iso2: "TD", name: "Chad", dialCode: "+235", timezones: ["Africa/Ndjamena"] },
  {
    iso2: "TF",
    name: "French Southern Territories",
    dialCode: "+262",
    timezones: ["Indian/Kerguelen"],
  },
  { iso2: "TG", name: "Togo", dialCode: "+228", timezones: ["Africa/Lome"] },
  { iso2: "TH", name: "Thailand", dialCode: "+66", timezones: ["Asia/Bangkok"] },
  { iso2: "TJ", name: "Tajikistan", dialCode: "+992", timezones: ["Asia/Dushanbe"] },
  { iso2: "TK", name: "Tokelau", dialCode: "+690", timezones: ["Pacific/Fakaofo"] },
  { iso2: "TL", name: "Timor-Leste", dialCode: "+670", timezones: ["Asia/Dili"] },
  { iso2: "TM", name: "Turkmenistan", dialCode: "+993", timezones: ["Asia/Ashgabat"] },
  { iso2: "TN", name: "Tunisia", dialCode: "+216", timezones: ["Africa/Tunis"] },
  { iso2: "TO", name: "Tonga", dialCode: "+676", timezones: ["Pacific/Tongatapu"] },
  { iso2: "TR", name: "Türkiye", dialCode: "+90", timezones: ["Europe/Istanbul"] },
  { iso2: "TT", name: "Trinidad and Tobago", dialCode: "+1", timezones: ["America/Port_of_Spain"] },
  { iso2: "TV", name: "Tuvalu", dialCode: "+688", timezones: ["Pacific/Funafuti"] },
  { iso2: "TW", name: "Taiwan", dialCode: "+886", timezones: ["Asia/Taipei"] },
  { iso2: "TZ", name: "Tanzania", dialCode: "+255", timezones: ["Africa/Dar_es_Salaam"] },
  {
    iso2: "UA",
    name: "Ukraine",
    dialCode: "+380",
    timezones: ["Europe/Kyiv", "Europe/Simferopol"],
  },
  { iso2: "UG", name: "Uganda", dialCode: "+256", timezones: ["Africa/Kampala"] },
  {
    iso2: "US",
    name: "United States",
    dialCode: "+1",
    timezones: [
      "America/New_York",
      "America/Chicago",
      "America/Denver",
      "America/Los_Angeles",
      "America/Anchorage",
      "America/Phoenix",
      "America/Detroit",
      "America/Indiana/Indianapolis",
      "America/Indiana/Knox",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Tell_City",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Menominee",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/Boise",
      "America/Juneau",
      "America/Sitka",
      "America/Metlakatla",
      "America/Yakutat",
      "America/Nome",
      "America/Adak",
      "Pacific/Honolulu",
    ],
  },
  { iso2: "UY", name: "Uruguay", dialCode: "+598", timezones: ["America/Montevideo"] },
  {
    iso2: "UZ",
    name: "Uzbekistan",
    dialCode: "+998",
    timezones: ["Asia/Samarkand", "Asia/Tashkent"],
  },
  { iso2: "VA", name: "Vatican City", dialCode: "+39", timezones: ["Europe/Vatican"] },
  {
    iso2: "VC",
    name: "Saint Vincent and the Grenadines",
    dialCode: "+1",
    timezones: ["America/St_Vincent"],
  },
  { iso2: "VE", name: "Venezuela", dialCode: "+58", timezones: ["America/Caracas"] },
  { iso2: "VG", name: "British Virgin Islands", dialCode: "+1", timezones: ["America/Tortola"] },
  { iso2: "VI", name: "U.S. Virgin Islands", dialCode: "+1", timezones: ["America/St_Thomas"] },
  { iso2: "VN", name: "Vietnam", dialCode: "+84", timezones: ["Asia/Ho_Chi_Minh"] },
  { iso2: "VU", name: "Vanuatu", dialCode: "+678", timezones: ["Pacific/Efate"] },
  { iso2: "WF", name: "Wallis and Futuna", dialCode: "+681", timezones: ["Pacific/Wallis"] },
  { iso2: "WS", name: "Samoa", dialCode: "+685", timezones: ["Pacific/Apia"] },
  { iso2: "YE", name: "Yemen", dialCode: "+967", timezones: ["Asia/Aden"] },
  { iso2: "YT", name: "Mayotte", dialCode: "+262", timezones: ["Indian/Mayotte"] },
  { iso2: "ZA", name: "South Africa", dialCode: "+27", timezones: ["Africa/Johannesburg"] },
  { iso2: "ZM", name: "Zambia", dialCode: "+260", timezones: ["Africa/Lusaka"] },
  { iso2: "ZW", name: "Zimbabwe", dialCode: "+263", timezones: ["Africa/Harare"] },
];

/** Lookup by ISO2. Returns undefined for unknown codes; callers fall back
 *  to the unfiltered timezone list and a free-form dial code. */
export function findCountryByIso(iso2: string | null | undefined): CountryRow | undefined {
  if (!iso2) return undefined;
  const upper = iso2.toUpperCase();
  return COUNTRIES.find((c) => c.iso2 === upper);
}

/** Lookup by display name. Used when reading a stored row back into the
 *  form (admin re-edit, future use) — the schema persists `country` as
 *  the display name, not the ISO code. */
export function findCountryByName(name: string | null | undefined): CountryRow | undefined {
  if (!name) return undefined;
  return COUNTRIES.find((c) => c.name === name);
}

/** Sorted name list for any UI that just needs strings. */
export const COUNTRY_NAMES: string[] = COUNTRIES.map((c) => c.name);

/** Convert an ISO 3166-1 alpha-2 code to its emoji flag.
 *
 * Uses the Unicode regional-indicator-symbol trick: a flag emoji is two
 * regional indicators glued together, where each indicator is the letter
 * shifted to the U+1F1E6..U+1F1FF block ('A' → 🇦, 'B' → 🇧, …). Render
 * support is universal in modern browsers + macOS / iOS; on Windows the
 * symbols render as plain letter pairs ("DE", "TR") which is degraded
 * but not broken — the picker UI still works because the country name
 * + dial code are always shown next to the flag.
 *
 * Returns the empty string for invalid input so callers can render
 * something sensible without null-checking. */
export function isoToFlag(iso2: string | null | undefined): string {
  if (!iso2 || iso2.length !== 2) return "";
  const upper = iso2.toUpperCase();
  if (!/^[A-Z]{2}$/.test(upper)) return "";
  const a = upper.charCodeAt(0) - 0x41 + 0x1f1e6;
  const b = upper.charCodeAt(1) - 0x41 + 0x1f1e6;
  return String.fromCodePoint(a, b);
}
